<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" Version="0.13.4" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TaskBridge.Api\TaskBridge.Api.csproj" />
    <ProjectReference Include="..\..\TaskBridge.Application\TaskBridge.Application.csproj" />
    <ProjectReference Include="..\..\TaskBridge.Contracts\TaskBridge.Contracts.csproj" />
    <ProjectReference Include="..\..\TaskBridge.DB\TaskBridge.DB.csproj" />
    <ProjectReference Include="..\..\TaskBridge.Desktop\TaskBridge.Desktop.csproj" />
    <ProjectReference Include="..\..\TaskBridge.Domain\TaskBridge.Domain.csproj" />
    <ProjectReference Include="..\..\TaskBridge.Infrastructure\TaskBridge.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
